### ISSUE TITLE
BuildNotify 0.2.8 does not work in Karmic with PyQt 4.6

### ISSUE THREAD

**Issue by anaynayak** [anaynayak/buildnotify#6]
Originally reported by: **Anay Nayak (Bitbucket: [Anay](https://bitbucket.org/Anay), GitHub: [Anay](https://github.com/anaynayak))**

----------------------------------------

Buildnotify fails with the following error in the log:

object has no attribute 'setInputMethodHints'. 

This method was probably introduced in PyQt4.7. Forcing PyQt 4.7 in karmic is not a solution as it breaks different dependencies. 

----------------------------------------
- Bitbucket: https://bitbucket.org/Anay/buildnotify/issue/6
